# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    build: db/.
    container_name: heroes-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: superman
    # volumes:
      # - ./data:/data/db
    ports:
      - "27017:27017"

